# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-secrets-abilities
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups: [""]
  resources:
  - namespaces
  verbs:
  - get
- apiGroups: [""]
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
---
## This cluster role is for testing the WAL + ownerRef rollback of orphaned k8s
## objects created during a creds/ call (it's missing serviceaccounts
## privileges)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-secrets-abilities-broken
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
---
## This cluster role is to allow tests to inspect k8s objects
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-capabilities
rules:
- apiGroups: [""]
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  - clusterrolebindings
  - clusterroles
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-role-list-pods
  namespace: test
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-cluster-role-list-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
